[package]
name = "cve_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
diesel = { version = "2.1.0", features = ["uuid", "serde_json", "chrono"] }
diesel-async = { version = "0.3.1", features = ["postgres", "deadpool"] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
dotenvy = "0.15.7"
poise = "0.5.5"
futures = "0.3.28"
deadpool = "0.9.5"
uuid = "0.8.2"
chrono = "0.4.26"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = { version = "1.0.103" }
