version: "3.9"
services:
  cve-bot-app-dev:
    tty: true
    env_file: .env
    build:
      context: .
      target: development
    depends_on: 
      - cve-bot-db-dev
    volumes:
        - .:/app
        - /target

  cve-bot-db-dev:
    env_file: .env
    image: postgres:alpine3.17
    restart: always
    volumes:
      - cve-bot-pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

  cve-bot-pgadmin-dev:
    env_file: .env
    depends_on: 
      - cve-bot-db-dev
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@example.com
      PGADMIN_DEFAULT_PASSWORD: wowsosecure
      PGADMIN_DISABLE_POSTFIX: '1'
      PGADMIN_LISTEN_ADDRESS: '127.0.0.1'
      PGADMIN_LISTEN_PORT: 8080
    volumes:
        - pgadmin:/var/lib/pgadmin
    network_mode: "host"

volumes:
  cve-bot-pgdata:
  pgadmin:
